Repository roopalisarode/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#4 created team prodcutivity log file
  Team_productivity_log.md
Labels: documentation

#7 added internationalization spec to the main page
  src/js/main.js
  tests/mywebclass_internationalization.spec.js
Labels: documentation

#43 Testing index.html file as a whole in general
  tests/mywebclass_index.spec.js
Labels: enhancement

#44 Performing SEO test on the privacy.html file
  tests/mywebclass_privacy_seo_test.spec.js
Labels: enhancement, legal compliance

#46 Performing Accessibility test on the content.html file
  tests/mywebclass_content_acccessibilty.spec.js
Labels: enhancement

#48 Performing Internationalization test on the content.html page
  tests/mywebclass_content_internationalization.spec.js
Labels: enhancement
